services:
    reservations:
        build:
            context: .
            dockerfile: "./apps/reservations/Dockerfile"
            target: development
        command: pnpm run start:dev reservations
        container_name: reservations_services
        environment:
            - NODE_ENV=development
        hostname: reservations
        ports:
            - "3000:3000"
        volumes:
            - .:/usr/src/app
        env_file:
            - ./apps/reservations/.env
        depends_on:
            - db
            - rabbitmq
    auth:
        build:
            context: .
            dockerfile: "./apps/auth/Dockerfile"
            target: development
        command: pnpm run start:dev auth
        container_name: auth_services
        environment:
            - NODE_ENV=development
        hostname: auth
        ports:
            - "3001:3001"
        volumes:
            - .:/usr/src/app
        env_file:
            - ./apps/auth/.env
        depends_on:
            - db
            - rabbitmq
    payments:
        build:
            context: .
            dockerfile: "./apps/payments/Dockerfile"
            target: development
        command: pnpm run start:dev payments
        container_name: payments_services
        environment:
            - NODE_ENV=development
        hostname: payments
        ports:
            - "3003:3003"
        volumes:
            - .:/usr/src/app
        env_file:
            - ./apps/payments/.env
        depends_on:
            - db
            - rabbitmq
    notifications:
        build:
            context: .
            dockerfile: "./apps/notifications/Dockerfile"
            target: development
        command: pnpm run start:dev notifications
        container_name: notifications_services
        environment:
            - NODE_ENV=development
        hostname: notifications
        ports:
            - "3004:3004"
        volumes:
            - .:/usr/src/app
        env_file:
            - ./apps/notifications/.env
        depends_on:
            - db
            - rabbitmq
    db:
        image: "mongo"
        restart: unless-stopped
        container_name: mongodb
        hostname: db
        ports:
            - 27017:27017
        env_file:
            - .env
        volumes:
            - mongodata:/data/db
            - mongodb_config:/data/configdb
        command: mongod
    rabbitmq:
        image: rabbitmq
        restart: unless-stopped
        container_name: rabbitmq
        hostname: rabbitmq
        ports:
            - 5672:5672

volumes:
    mongodata:
    mongodb_config:
