services:
    app:
        build:
            context: .
            dockerfile: "./apps/reservations/Dockerfile"
            target: qa
        command: pnpm run start:dev reservations
        environment:
            - NODE_ENV=qa
