version: '3.9'

services:
  app:
    build: .
    ports:
      - '3000:3000'
    volumes:
      - .:/app
    depends_on:
      - db
  db:
    image: 'mongo'
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: secret
    ports:
      - 27017:27017
    volumes:
      - mongodata:/data/db
      - mongodb_config:/data/configdb
    command: mongod

volumes :
  mongodata:
  mongodb_config: